###############################################################################
# Created by write_sdc
###############################################################################
current_design alu_top
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 3.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {a[0]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {a[1]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {a[2]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {a[3]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {a[4]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {a[5]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {a[6]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {a[7]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {b[0]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {b[1]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {b[2]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {b[3]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {b[4]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {b[5]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {b[6]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {b[7]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {op[0]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {op[1]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {op[2]}]
set_input_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_output_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {carry}]
set_output_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {negative}]
set_output_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {overflow}]
set_output_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {y[0]}]
set_output_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {y[1]}]
set_output_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {y[2]}]
set_output_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {y[3]}]
set_output_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {y[4]}]
set_output_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {y[5]}]
set_output_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {y[6]}]
set_output_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {y[7]}]
set_output_delay 0.6000 -clock [get_clocks {clk}] -add_delay [get_ports {zero}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {carry}]
set_load -pin_load 0.0334 [get_ports {negative}]
set_load -pin_load 0.0334 [get_ports {overflow}]
set_load -pin_load 0.0334 [get_ports {zero}]
set_load -pin_load 0.0334 [get_ports {y[7]}]
set_load -pin_load 0.0334 [get_ports {y[6]}]
set_load -pin_load 0.0334 [get_ports {y[5]}]
set_load -pin_load 0.0334 [get_ports {y[4]}]
set_load -pin_load 0.0334 [get_ports {y[3]}]
set_load -pin_load 0.0334 [get_ports {y[2]}]
set_load -pin_load 0.0334 [get_ports {y[1]}]
set_load -pin_load 0.0334 [get_ports {y[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst_n}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {op[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {op[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {op[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
