/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module alu_top(clk, rst_n, a, b, op, y, carry, overflow, zero, negative);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input [2:0] op;
  wire [2:0] op;
  output [7:0] y;
  wire [7:0] y;
  output carry;
  wire carry;
  output overflow;
  wire overflow;
  output zero;
  wire zero;
  output negative;
  wire negative;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire \a_q[0] ;
  wire \a_q[1] ;
  wire \a_q[2] ;
  wire \a_q[3] ;
  wire \a_q[4] ;
  wire \a_q[5] ;
  wire \a_q[6] ;
  wire \a_q[7] ;
  wire \b_q[0] ;
  wire \b_q[1] ;
  wire \b_q[2] ;
  wire \b_q[3] ;
  wire \b_q[4] ;
  wire \b_q[5] ;
  wire \b_q[6] ;
  wire \b_q[7] ;
  wire \op_q[0] ;
  wire \op_q[1] ;
  wire \op_q[2] ;
  sky130_fd_sc_hd__a21o_2 _148_ (
    .A1(_134_),
    .A2(_048_),
    .B1(_095_),
    .X(_096_)
  );
  sky130_fd_sc_hd__nor2_2 _149_ (
    .A(_055_),
    .B(_091_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a211o_2 _150_ (
    .A1(_124_),
    .A2(_092_),
    .B1(_096_),
    .C1(_097_),
    .X(_098_)
  );
  sky130_fd_sc_hd__o211a_2 _151_ (
    .A1(\a_q[6] ),
    .A2(_049_),
    .B1(_098_),
    .C1(rst_n),
    .X(_006_)
  );
  sky130_fd_sc_hd__nand2_2 _152_ (
    .A(_129_),
    .B(_130_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand3b_2 _153_ (
    .A_N(_099_),
    .B(_039_),
    .C(_133_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a21bo_2 _154_ (
    .A1(_133_),
    .A2(_039_),
    .B1_N(_099_),
    .X(_101_)
  );
  sky130_fd_sc_hd__o21a_2 _155_ (
    .A1(\a_q[6] ),
    .A2(\b_q[6] ),
    .B1(_043_),
    .X(_102_)
  );
  sky130_fd_sc_hd__a21oi_2 _156_ (
    .A1(\a_q[5] ),
    .A2(_057_),
    .B1(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__o211a_2 _157_ (
    .A1(\a_q[6] ),
    .A2(_050_),
    .B1(_103_),
    .C1(_049_),
    .X(_104_)
  );
  sky130_fd_sc_hd__o21ai_2 _158_ (
    .A1(_055_),
    .A2(_099_),
    .B1(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a21o_2 _159_ (
    .A1(_131_),
    .A2(_048_),
    .B1(_105_),
    .X(_106_)
  );
  sky130_fd_sc_hd__a31o_2 _160_ (
    .A1(_124_),
    .A2(_100_),
    .A3(_101_),
    .B1(_106_),
    .X(_107_)
  );
  sky130_fd_sc_hd__o211a_2 _161_ (
    .A1(\a_q[7] ),
    .A2(_049_),
    .B1(_107_),
    .C1(rst_n),
    .X(_007_)
  );
  sky130_fd_sc_hd__and2_2 _162_ (
    .A(_041_),
    .B(_042_),
    .X(_008_)
  );
  sky130_fd_sc_hd__nand2b_2 _163_ (
    .A_N(_127_),
    .B(_042_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__xnor2_2 _164_ (
    .A(_040_),
    .B(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__a21oi_2 _165_ (
    .A1(\b_q[7] ),
    .A2(\a_q[7] ),
    .B1(_055_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o22a_2 _166_ (
    .A1(\b_q[7] ),
    .A2(\a_q[7] ),
    .B1(_043_),
    .B2(_110_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nor2_2 _167_ (
    .A(\a_q[7] ),
    .B(_050_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a32o_2 _168_ (
    .A1(\b_q[7] ),
    .A2(\a_q[7] ),
    .A3(_048_),
    .B1(_057_),
    .B2(\a_q[6] ),
    .X(_113_)
  );
  sky130_fd_sc_hd__or3_2 _169_ (
    .A(_111_),
    .B(_112_),
    .C(_113_),
    .X(_114_)
  );
  sky130_fd_sc_hd__a21o_2 _170_ (
    .A1(_124_),
    .A2(_109_),
    .B1(_114_),
    .X(_115_)
  );
  sky130_fd_sc_hd__and2_2 _171_ (
    .A(rst_n),
    .B(_115_),
    .X(_010_)
  );
  sky130_fd_sc_hd__a2111o_2 _172_ (
    .A1(_081_),
    .A2(_082_),
    .B1(_052_),
    .C1(_063_),
    .D1(_073_),
    .X(_116_)
  );
  sky130_fd_sc_hd__a22o_2 _173_ (
    .A1(_089_),
    .A2(_090_),
    .B1(_116_),
    .B2(rst_n),
    .X(_117_)
  );
  sky130_fd_sc_hd__a2111oi_2 _174_ (
    .A1(rst_n),
    .A2(_115_),
    .B1(_117_),
    .C1(_006_),
    .D1(_007_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__and2_2 _175_ (
    .A(rst_n),
    .B(a[0]),
    .X(_011_)
  );
  sky130_fd_sc_hd__and2_2 _176_ (
    .A(rst_n),
    .B(a[1]),
    .X(_012_)
  );
  sky130_fd_sc_hd__and2_2 _177_ (
    .A(rst_n),
    .B(a[2]),
    .X(_013_)
  );
  sky130_fd_sc_hd__and2_2 _178_ (
    .A(rst_n),
    .B(a[3]),
    .X(_014_)
  );
  sky130_fd_sc_hd__and2_2 _179_ (
    .A(rst_n),
    .B(a[4]),
    .X(_015_)
  );
  sky130_fd_sc_hd__and2_2 _180_ (
    .A(rst_n),
    .B(a[5]),
    .X(_016_)
  );
  sky130_fd_sc_hd__and2_2 _181_ (
    .A(rst_n),
    .B(a[6]),
    .X(_017_)
  );
  sky130_fd_sc_hd__and2_2 _182_ (
    .A(rst_n),
    .B(a[7]),
    .X(_018_)
  );
  sky130_fd_sc_hd__and2_2 _183_ (
    .A(rst_n),
    .B(b[0]),
    .X(_019_)
  );
  sky130_fd_sc_hd__and2_2 _184_ (
    .A(rst_n),
    .B(b[1]),
    .X(_020_)
  );
  sky130_fd_sc_hd__and2_2 _185_ (
    .A(rst_n),
    .B(b[2]),
    .X(_021_)
  );
  sky130_fd_sc_hd__and2_2 _186_ (
    .A(rst_n),
    .B(b[3]),
    .X(_022_)
  );
  sky130_fd_sc_hd__and2_2 _187_ (
    .A(rst_n),
    .B(b[4]),
    .X(_023_)
  );
  sky130_fd_sc_hd__and2_2 _188_ (
    .A(rst_n),
    .B(b[5]),
    .X(_024_)
  );
  sky130_fd_sc_hd__and2_2 _189_ (
    .A(rst_n),
    .B(b[6]),
    .X(_025_)
  );
  sky130_fd_sc_hd__and2_2 _190_ (
    .A(rst_n),
    .B(b[7]),
    .X(_026_)
  );
  sky130_fd_sc_hd__and2_2 _191_ (
    .A(rst_n),
    .B(op[0]),
    .X(_027_)
  );
  sky130_fd_sc_hd__and2_2 _192_ (
    .A(rst_n),
    .B(op[1]),
    .X(_028_)
  );
  sky130_fd_sc_hd__and2_2 _193_ (
    .A(rst_n),
    .B(op[2]),
    .X(_029_)
  );
  sky130_fd_sc_hd__inv_2 _194_ (
    .A(\a_q[7] ),
    .Y(_118_)
  );
  sky130_fd_sc_hd__inv_2 _195_ (
    .A(\a_q[6] ),
    .Y(_119_)
  );
  sky130_fd_sc_hd__inv_2 _196_ (
    .A(\a_q[5] ),
    .Y(_120_)
  );
  sky130_fd_sc_hd__inv_2 _197_ (
    .A(\a_q[4] ),
    .Y(_121_)
  );
  sky130_fd_sc_hd__inv_2 _198_ (
    .A(\a_q[3] ),
    .Y(_122_)
  );
  sky130_fd_sc_hd__inv_2 _199_ (
    .A(\a_q[2] ),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nor2_2 _200_ (
    .A(\op_q[1] ),
    .B(\op_q[2] ),
    .Y(_124_)
  );
  sky130_fd_sc_hd__or3b_2 _201_ (
    .A(\op_q[1] ),
    .B(\op_q[2] ),
    .C_N(\op_q[0] ),
    .X(_125_)
  );
  sky130_fd_sc_hd__xor2_2 _202_ (
    .A(\b_q[7] ),
    .B(_125_),
    .X(_126_)
  );
  sky130_fd_sc_hd__nor2_2 _203_ (
    .A(_118_),
    .B(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__xor2_2 _204_ (
    .A(\b_q[6] ),
    .B(_125_),
    .X(_128_)
  );
  sky130_fd_sc_hd__nand2_2 _205_ (
    .A(_119_),
    .B(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__or2_2 _206_ (
    .A(_119_),
    .B(_128_),
    .X(_130_)
  );
  sky130_fd_sc_hd__inv_2 _207_ (
    .A(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__xor2_2 _208_ (
    .A(\b_q[5] ),
    .B(_125_),
    .X(_132_)
  );
  sky130_fd_sc_hd__nand2_2 _209_ (
    .A(_120_),
    .B(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nor2_2 _210_ (
    .A(_120_),
    .B(_132_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__or2_2 _211_ (
    .A(_120_),
    .B(_132_),
    .X(_135_)
  );
  sky130_fd_sc_hd__xor2_2 _212_ (
    .A(\b_q[4] ),
    .B(_125_),
    .X(_136_)
  );
  sky130_fd_sc_hd__nand2_2 _213_ (
    .A(_121_),
    .B(_136_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__or2_2 _214_ (
    .A(_121_),
    .B(_136_),
    .X(_138_)
  );
  sky130_fd_sc_hd__inv_2 _215_ (
    .A(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__xor2_2 _216_ (
    .A(\b_q[3] ),
    .B(_125_),
    .X(_140_)
  );
  sky130_fd_sc_hd__nand2_2 _217_ (
    .A(_122_),
    .B(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor2_2 _218_ (
    .A(_122_),
    .B(_140_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__or2_2 _219_ (
    .A(_122_),
    .B(_140_),
    .X(_143_)
  );
  sky130_fd_sc_hd__xor2_2 _220_ (
    .A(\b_q[2] ),
    .B(_125_),
    .X(_144_)
  );
  sky130_fd_sc_hd__nand2_2 _221_ (
    .A(_123_),
    .B(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nor2_2 _222_ (
    .A(_123_),
    .B(_144_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__or2_2 _223_ (
    .A(_123_),
    .B(_144_),
    .X(_147_)
  );
  sky130_fd_sc_hd__xnor2_2 _224_ (
    .A(\b_q[1] ),
    .B(_125_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__or2_2 _225_ (
    .A(\a_q[1] ),
    .B(_030_),
    .X(_031_)
  );
  sky130_fd_sc_hd__nand2_2 _226_ (
    .A(\a_q[0] ),
    .B(\b_q[0] ),
    .Y(_032_)
  );
  sky130_fd_sc_hd__o21ai_2 _227_ (
    .A1(\b_q[0] ),
    .A2(_125_),
    .B1(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a21o_2 _228_ (
    .A1(\a_q[1] ),
    .A2(_030_),
    .B1(_033_),
    .X(_034_)
  );
  sky130_fd_sc_hd__a31o_2 _229_ (
    .A1(_145_),
    .A2(_031_),
    .A3(_034_),
    .B1(_146_),
    .X(_035_)
  );
  sky130_fd_sc_hd__a311o_2 _230_ (
    .A1(_145_),
    .A2(_031_),
    .A3(_034_),
    .B1(_146_),
    .C1(_142_),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand2_2 _231_ (
    .A(_141_),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a31o_2 _232_ (
    .A1(_137_),
    .A2(_141_),
    .A3(_036_),
    .B1(_139_),
    .X(_038_)
  );
  sky130_fd_sc_hd__a311o_2 _233_ (
    .A1(_137_),
    .A2(_141_),
    .A3(_036_),
    .B1(_139_),
    .C1(_134_),
    .X(_039_)
  );
  sky130_fd_sc_hd__a31o_2 _234_ (
    .A1(_129_),
    .A2(_133_),
    .A3(_039_),
    .B1(_131_),
    .X(_040_)
  );
  sky130_fd_sc_hd__o211a_2 _235_ (
    .A1(_127_),
    .A2(_040_),
    .B1(rst_n),
    .C1(_124_),
    .X(_041_)
  );
  sky130_fd_sc_hd__nand2_2 _236_ (
    .A(_118_),
    .B(_126_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a21boi_2 _237_ (
    .A1(_040_),
    .A2(_042_),
    .B1_N(_041_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__and3b_2 _238_ (
    .A_N(\op_q[2] ),
    .B(\op_q[0] ),
    .C(\op_q[1] ),
    .X(_043_)
  );
  sky130_fd_sc_hd__nand2_2 _239_ (
    .A(\op_q[0] ),
    .B(\op_q[2] ),
    .Y(_044_)
  );
  sky130_fd_sc_hd__and3b_2 _240_ (
    .A_N(\op_q[1] ),
    .B(_032_),
    .C(_044_),
    .X(_045_)
  );
  sky130_fd_sc_hd__o22a_2 _241_ (
    .A1(\a_q[0] ),
    .A2(\b_q[0] ),
    .B1(_043_),
    .B2(_045_),
    .X(_046_)
  );
  sky130_fd_sc_hd__or3b_2 _242_ (
    .A(\op_q[0] ),
    .B(\op_q[2] ),
    .C_N(\op_q[1] ),
    .X(_047_)
  );
  sky130_fd_sc_hd__inv_2 _243_ (
    .A(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand3_2 _244_ (
    .A(\op_q[1] ),
    .B(\op_q[0] ),
    .C(\op_q[2] ),
    .Y(_049_)
  );
  sky130_fd_sc_hd__or2_2 _245_ (
    .A(\op_q[1] ),
    .B(_044_),
    .X(_050_)
  );
  sky130_fd_sc_hd__o221ai_2 _246_ (
    .A1(_032_),
    .A2(_047_),
    .B1(_050_),
    .B2(\a_q[0] ),
    .C1(_049_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o22a_2 _247_ (
    .A1(\a_q[1] ),
    .A2(_049_),
    .B1(_051_),
    .B2(_046_),
    .X(_052_)
  );
  sky130_fd_sc_hd__and2_2 _248_ (
    .A(rst_n),
    .B(_052_),
    .X(_001_)
  );
  sky130_fd_sc_hd__xnor2_2 _249_ (
    .A(\a_q[1] ),
    .B(_030_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__xnor2_2 _250_ (
    .A(_033_),
    .B(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__or3b_2 _251_ (
    .A(\op_q[1] ),
    .B(\op_q[0] ),
    .C_N(\op_q[2] ),
    .X(_055_)
  );
  sky130_fd_sc_hd__nor2_2 _252_ (
    .A(_053_),
    .B(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__and3b_2 _253_ (
    .A_N(\op_q[0] ),
    .B(\op_q[2] ),
    .C(\op_q[1] ),
    .X(_057_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _254_ (
    .A1_N(\a_q[1] ),
    .A2_N(_050_),
    .B1(_057_),
    .B2(\a_q[0] ),
    .X(_058_)
  );
  sky130_fd_sc_hd__o311a_2 _255_ (
    .A1(\op_q[2] ),
    .A2(\a_q[1] ),
    .A3(\b_q[1] ),
    .B1(\op_q[0] ),
    .C1(\op_q[1] ),
    .X(_059_)
  );
  sky130_fd_sc_hd__and3_2 _256_ (
    .A(\a_q[1] ),
    .B(_030_),
    .C(_048_),
    .X(_060_)
  );
  sky130_fd_sc_hd__or3_2 _257_ (
    .A(_058_),
    .B(_059_),
    .C(_060_),
    .X(_061_)
  );
  sky130_fd_sc_hd__a211o_2 _258_ (
    .A1(_124_),
    .A2(_054_),
    .B1(_056_),
    .C1(_061_),
    .X(_062_)
  );
  sky130_fd_sc_hd__o21a_2 _259_ (
    .A1(\a_q[2] ),
    .A2(_049_),
    .B1(_062_),
    .X(_063_)
  );
  sky130_fd_sc_hd__and2_2 _260_ (
    .A(rst_n),
    .B(_063_),
    .X(_002_)
  );
  sky130_fd_sc_hd__nand2_2 _261_ (
    .A(_145_),
    .B(_147_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand4_2 _262_ (
    .A(_145_),
    .B(_147_),
    .C(_031_),
    .D(_034_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a22o_2 _263_ (
    .A1(_145_),
    .A2(_147_),
    .B1(_031_),
    .B2(_034_),
    .X(_066_)
  );
  sky130_fd_sc_hd__and3_2 _264_ (
    .A(_124_),
    .B(_065_),
    .C(_066_),
    .X(_067_)
  );
  sky130_fd_sc_hd__nor2_2 _265_ (
    .A(_147_),
    .B(_047_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_2 _266_ (
    .A(\a_q[1] ),
    .B(_057_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__o21ai_2 _267_ (
    .A1(\a_q[2] ),
    .A2(\b_q[2] ),
    .B1(_043_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__o211a_2 _268_ (
    .A1(\a_q[2] ),
    .A2(_050_),
    .B1(_069_),
    .C1(_070_),
    .X(_071_)
  );
  sky130_fd_sc_hd__o211ai_2 _269_ (
    .A1(_055_),
    .A2(_064_),
    .B1(_071_),
    .C1(_049_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__o32a_2 _270_ (
    .A1(_067_),
    .A2(_068_),
    .A3(_072_),
    .B1(_049_),
    .B2(\a_q[3] ),
    .X(_073_)
  );
  sky130_fd_sc_hd__and2_2 _271_ (
    .A(rst_n),
    .B(_073_),
    .X(_003_)
  );
  sky130_fd_sc_hd__nand2_2 _272_ (
    .A(_141_),
    .B(_143_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__xnor2_2 _273_ (
    .A(_035_),
    .B(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__o21a_2 _274_ (
    .A1(\b_q[3] ),
    .A2(\a_q[3] ),
    .B1(_043_),
    .X(_076_)
  );
  sky130_fd_sc_hd__o21ai_2 _275_ (
    .A1(\a_q[3] ),
    .A2(_044_),
    .B1(_049_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a211o_2 _276_ (
    .A1(\a_q[2] ),
    .A2(_057_),
    .B1(_076_),
    .C1(_077_),
    .X(_078_)
  );
  sky130_fd_sc_hd__a21o_2 _277_ (
    .A1(_142_),
    .A2(_048_),
    .B1(_078_),
    .X(_079_)
  );
  sky130_fd_sc_hd__nor2_2 _278_ (
    .A(_055_),
    .B(_074_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__a211o_2 _279_ (
    .A1(_124_),
    .A2(_075_),
    .B1(_079_),
    .C1(_080_),
    .X(_081_)
  );
  sky130_fd_sc_hd__or2_2 _280_ (
    .A(\a_q[4] ),
    .B(_049_),
    .X(_082_)
  );
  sky130_fd_sc_hd__and3_2 _281_ (
    .A(rst_n),
    .B(_081_),
    .C(_082_),
    .X(_004_)
  );
  sky130_fd_sc_hd__nand2_2 _282_ (
    .A(_137_),
    .B(_138_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__xor2_2 _283_ (
    .A(_037_),
    .B(_083_),
    .X(_084_)
  );
  sky130_fd_sc_hd__o21a_2 _284_ (
    .A1(\b_q[4] ),
    .A2(\a_q[4] ),
    .B1(_043_),
    .X(_085_)
  );
  sky130_fd_sc_hd__o21ai_2 _285_ (
    .A1(\a_q[4] ),
    .A2(_044_),
    .B1(_049_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__a211o_2 _286_ (
    .A1(\a_q[3] ),
    .A2(_057_),
    .B1(_085_),
    .C1(_086_),
    .X(_087_)
  );
  sky130_fd_sc_hd__o22ai_2 _287_ (
    .A1(_138_),
    .A2(_047_),
    .B1(_055_),
    .B2(_083_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a211o_2 _288_ (
    .A1(_124_),
    .A2(_084_),
    .B1(_087_),
    .C1(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd__o21a_2 _289_ (
    .A1(\a_q[5] ),
    .A2(_049_),
    .B1(rst_n),
    .X(_090_)
  );
  sky130_fd_sc_hd__and2_2 _290_ (
    .A(_089_),
    .B(_090_),
    .X(_005_)
  );
  sky130_fd_sc_hd__nand2_2 _291_ (
    .A(_133_),
    .B(_135_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__xnor2_2 _292_ (
    .A(_038_),
    .B(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__o21a_2 _293_ (
    .A1(\b_q[5] ),
    .A2(\a_q[5] ),
    .B1(_043_),
    .X(_093_)
  );
  sky130_fd_sc_hd__o21ai_2 _294_ (
    .A1(\a_q[5] ),
    .A2(_044_),
    .B1(_049_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a211o_2 _295_ (
    .A1(\a_q[4] ),
    .A2(_057_),
    .B1(_093_),
    .C1(_094_),
    .X(_095_)
  );
  sky130_fd_sc_hd__dfxtp_2 _296_ (
    .CLK(clk),
    .D(_000_),
    .Q(overflow)
  );
  sky130_fd_sc_hd__dfxtp_2 _297_ (
    .CLK(clk),
    .D(_001_),
    .Q(y[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _298_ (
    .CLK(clk),
    .D(_002_),
    .Q(y[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _299_ (
    .CLK(clk),
    .D(_003_),
    .Q(y[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _300_ (
    .CLK(clk),
    .D(_004_),
    .Q(y[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _301_ (
    .CLK(clk),
    .D(_005_),
    .Q(y[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _302_ (
    .CLK(clk),
    .D(_006_),
    .Q(y[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _303_ (
    .CLK(clk),
    .D(_007_),
    .Q(y[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _304_ (
    .CLK(clk),
    .D(_008_),
    .Q(carry)
  );
  sky130_fd_sc_hd__dfxtp_2 _305_ (
    .CLK(clk),
    .D(_009_),
    .Q(zero)
  );
  sky130_fd_sc_hd__dfxtp_2 _306_ (
    .CLK(clk),
    .D(_010_),
    .Q(negative)
  );
  sky130_fd_sc_hd__dfxtp_2 _307_ (
    .CLK(clk),
    .D(_011_),
    .Q(\a_q[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _308_ (
    .CLK(clk),
    .D(_012_),
    .Q(\a_q[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _309_ (
    .CLK(clk),
    .D(_013_),
    .Q(\a_q[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _310_ (
    .CLK(clk),
    .D(_014_),
    .Q(\a_q[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _311_ (
    .CLK(clk),
    .D(_015_),
    .Q(\a_q[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _312_ (
    .CLK(clk),
    .D(_016_),
    .Q(\a_q[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _313_ (
    .CLK(clk),
    .D(_017_),
    .Q(\a_q[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _314_ (
    .CLK(clk),
    .D(_018_),
    .Q(\a_q[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _315_ (
    .CLK(clk),
    .D(_019_),
    .Q(\b_q[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _316_ (
    .CLK(clk),
    .D(_020_),
    .Q(\b_q[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _317_ (
    .CLK(clk),
    .D(_021_),
    .Q(\b_q[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _318_ (
    .CLK(clk),
    .D(_022_),
    .Q(\b_q[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _319_ (
    .CLK(clk),
    .D(_023_),
    .Q(\b_q[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _320_ (
    .CLK(clk),
    .D(_024_),
    .Q(\b_q[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _321_ (
    .CLK(clk),
    .D(_025_),
    .Q(\b_q[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _322_ (
    .CLK(clk),
    .D(_026_),
    .Q(\b_q[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _323_ (
    .CLK(clk),
    .D(_027_),
    .Q(\op_q[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _324_ (
    .CLK(clk),
    .D(_028_),
    .Q(\op_q[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _325_ (
    .CLK(clk),
    .D(_029_),
    .Q(\op_q[2] )
  );
  sky130_fd_sc_hd__buf_2 _326_ (
    .A(negative),
    .X(y[7])
  );
endmodule
