// Auto-generated by LibreLane
module alu_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input[7:0] a,
  input[7:0] b,
  input[2:0] op,
  output[7:0] y,
  output carry,
  output overflow,
  output zero,
  output negative
);
endmodule
